version: '3.8'

services:
    
    postgres:        
        image: postgres:14.5
        ports:
        - 5432:5432
      
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: hotelbookingdb

       
      
    hotelbooking:        
        build: .  #Docker file is in current directory
        #image: imagename:tag
        ports:
        - 8070:8070 #Mapping host port with container port because app will run at 8070 inside container and we want it to accept traffic from host(OUTSIDE CONTAINER)
     
  
